### ISSUE TITLE
Exception when adding liveRecording param

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-uxkit-cordova#14]
**Describe the bug**

liveRecording seems to not being supported
It works well with the same code when removing the "params" attribute in create() method

**Expected Behaviour**

support liveRecording param on Android

**Minimalistic code (recommended)**

```
const { Voxeet, UserType } = VoxeetSDK;

Voxeet.initializeToken("YOUR_CONSUMER_KEY", "YOUR_CONSUMER_SECRET")
.then(() => Voxeet.defaultBuiltInSpeaker(true))
.then(() => Voxeet.defaultVideo(true))
.then(() => Voxeet.connect(new UserInfo(id, name, avatar)))
.then(() => Voxeet.create({alias: conferenceAlias, params: {liveRecording: true}}))
.then(result => Voxeet.join(result.conferenceId))
.catch(err => alert(err));
```

**Android Logs**
```
0427/6792 clientId=android.media.AudioManager@b57460bcom.voxeet.audio.focus.AudioFocusRequest26$1@3025ce8 req=1 flags=0x3
07-23 12:48:01.642  1168  1178 I HwPCUtils#HwMediaFocusControl: isAppInExternalDisplay aa = AudioAttributes: usage=2 content=1 flags=0x0 tags= bundle=null, clientId = android.media.AudioManager@b57460bcom.voxeet.audio.focus.AudioFocusRequest26$1@3025ce8, pkgName = com.ts.tsmobile, mInDestopMode = false, uid = 10427
07-23 12:48:01.642  1168  1178 I HwPCUtils#MediaFocusControl:  requestAudioFocus isInExternalDisplay = false
07-23 12:48:01.642  1168  1178 I MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.media.AudioManager@b57460bcom.voxeet.audio.focus.AudioFocusRequest26$1@3025ce8
07-23 12:48:01.642  1168  1168 I HwDubaiService: BroadcastReceiver android.media.VOLUME_CHANGED_ACTION
07-23 12:48:01.643  6792  6792 D VoxeetConferenceView: displayView: com.voxeet.toolkit.implementation.overlays.VoxeetOverlayToggleView{94d4fe V.E...... ......I. 0,0-0,0} false true
07-23 12:48:01.643  6792  6792 D VoxeetConferenceBarView: isListener: null
07-23 12:48:01.645  6792  6792 D VoxeetConferenceView: onConferenceCreating: 0 8
07-23 12:48:01.645  6792  6792 D CreateConferencePromiseable: Attempting to create mConferene alias:=271308
07-23 12:48:01.696  6792  6792 D AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@b57460bcom.voxeet.audio.focus.AudioFocusRequest26$1@3025ce8
07-23 12:48:01.696  6792  6792 D AudioFocusRequest: onAudioFocusChange: -1
07-23 12:48:01.706   728   889 W JankService: processEntry, not beta version or commercial log off
07-23 12:48:01.771  1168  1168 I MQoS    : onSignal: mSubId=0,currDataSubID=0
07-23 12:48:01.772  1168  1168 I MQoS    : received cell-signal:5
07-23 12:48:01.778  1774  1878 I HwMobileSignalController(0): subId:0 phoneType:1 networktype:13 targetClass:3 masterLevel:4 slaveLevel:-1
07-23 12:48:02.040  6792  7518 D VoxeetHttp: intercept: builder
07-23 12:48:02.040  6792  7518 D TokenResponseProvider: execute: intercept tokenResponse := {access_token := XXX==refresh_token := null}
07-23 12:48:02.113  1168  1655 I HwAudioService: isAdjustVolumeEnable,mEnableAdjustVolume:true
07-23 12:48:02.252  6792  6792 D HttpException: dumpErrorResponse: http call exception := {"type":"ErrorResponse","error_code":1,"error_reason":"internal_server_error","error_description":"Server has a problem"}
07-23 12:48:02.253  6792  6792 D HttpException: dumpErrorResponse: http call exception :=
07-23 12:48:02.253  6792  6792 W System.err: com.voxeet.sdk.events.error.HttpException
07-23 12:48:02.254  6792  6792 W System.err: 	at com.voxeet.sdk.core.http.HttpHelper$1.onResponse(HttpHelper.java:24)
07-23 12:48:02.254  6792  6792 W System.err: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
07-23 12:48:02.254  6792  6792 W System.err: 	at android.os.Handler.handleCallback(Handler.java:808)
07-23 12:48:02.254  6792  6792 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:101)
07-23 12:48:02.254  6792  6792 W System.err: 	at android.os.Looper.loop(Looper.java:166)
07-23 12:48:02.255  6792  6792 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
07-23 12:48:02.255  6792  6792 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 12:48:02.255  6792  6792 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
07-23 12:48:02.255  6792  6792 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
07-23 12:48:02.255  6792  6792 D CreateConferencePromiseable: internalCreate onFailure: conference creation failed ! but retry... now...
07-23 12:48:02.271  6792  7518 D VoxeetHttp: intercept: builder
07-23 12:48:02.271  6792  7518 D TokenResponseProvider: execute: intercept tokenResponse := {access_token := XXX==refresh_token := null}
07-23 12:48:02.452  6792  6792 D HttpException: dumpErrorResponse: http call exception := {"type":"ErrorResponse","error_code":1,"error_reason":"internal_server_error","error_description":"Server has a problem"}
07-23 12:48:02.452  6792  6792 D HttpException: dumpErrorResponse: http call exception :=
07-23 12:48:02.453  6792  6792 W System.err: com.voxeet.sdk.events.error.HttpException
07-23 12:48:02.453  6792  6792 W System.err: 	at com.voxeet.sdk.core.http.HttpHelper$1.onResponse(HttpHelper.java:24)
07-23 12:48:02.453  6792  6792 W System.err: 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
07-23 12:48:02.453  6792  6792 W System.err: 	at android.os.Handler.handleCallback(Handler.java:808)
07-23 12:48:02.453  6792  6792 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:101)
07-23 12:48:02.454  6792  6792 W System.err: 	at android.os.Looper.loop(Looper.java:166)
07-23 12:48:02.454  6792  6792 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
07-23 12:48:02.454  6792  6792 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 12:48:02.454  6792  6792 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
07-23 12:48:02.454  6792  6792 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
07-23 12:48:02.454  6792  6792 D CreateConferencePromiseable: internalCreate onFailure: conference creation failed ! but no retry... quit...
07-23 12:48:02.455  6792  6792 D AbstractVoxeetService: handleError: HttpException
07-23 12:48:02.456  6792  6792 D SoundPool: onEvent: ConferenceCreatedError
07-23 12:48:02.457  6792  6792 D SoundPool: stop: []
07-23 12:48:02.457  6792  6792 D SoundPool: stop: testing leave.mp3 2
07-23 12:48:02.457  6792  6792 D SoundPool: stop: testing out.mp3 1
07-23 12:48:02.467  6792  6792 D VoxeetConferenceView: run: AbstractConferenceToolkitController should release view VoxeetOverlayToggleView
07-23 12:48:02.590  6792  6792 D SystemWebChromeClient: http://localhost/build/main.js: Line 1344 : VideoconfService - create conf err
```

**Specifications**

  - Devices: Honor 7X
  - OS: Android
  - Platform: Android 8.0.0

**Comment by codlab** [comment]
Bundled within the 1.2.2, this bug is fixed
