### ISSUE TITLE
 java.lang.RuntimeException: Unable to instantiate service com.voxeet.toolkit.notification.CordovaFirebaseMessagingService

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-uxkit-cordova#17]
**Describe the bug**

Google play automatic tests fail on multiple devices : 
- Mate 9 Android 7.1
- Pixel Android 7.1
- Pixel 2 Android 8.1
- Pixel 3 Android 9

```
09-17 08:58:52.992: I/Finsky(9149): [1] sah.a(22): Running job: 10-10
09-17 08:58:52.994: I/art(9149): Waiting for a blocking GC DisableMovingGc
09-17 08:58:52.995: I/art(9149): Waiting for a blocking GC DisableMovingGc
09-17 08:58:53.001: I/Finsky(9149): [1] sao.handleMessage(102): RunningQueue size: 4, PendingQueue size: 37
09-17 08:58:53.008: I/Finsky(9149): [1] sao.handleMessage(111): Running queue: 10-1 10-2 10-8 10-10 
09-17 08:58:53.019: I/art(9149): WaitForGcToComplete blocked for 24.698ms for cause DisableMovingGc
09-17 08:58:53.019: I/art(9149): Starting a blocking GC DisableMovingGc
09-17 08:58:53.021: I/art(9149): WaitForGcToComplete blocked for 26.005ms for cause DisableMovingGc
09-17 08:58:53.021: I/art(9149): Starting a blocking GC DisableMovingGc
09-17 08:58:53.044: D/AndroidRuntime(10123): Shutting down VM
09-17 08:58:53.044: D/AndroidRuntime(10123): --------- beginning of crash
09-17 08:58:53.044: E/AndroidRuntime(10123): FATAL EXCEPTION: main
09-17 08:58:53.044: E/AndroidRuntime(10123): Process: com.*.*, PID: 10123
09-17 08:58:53.044: E/AndroidRuntime(10123): java.lang.RuntimeException: Unable to instantiate service com.voxeet.toolkit.notification.CordovaFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.voxeet.toolkit.notification.CordovaFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.*.*-1/base.apk"],nativeLibraryDirectories=[/data/app/com.*.*-1/lib/arm64, /data/app/com.*.*-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3168)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at android.os.Looper.loop(Looper.java:154)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at java.lang.reflect.Method.invoke(Native Method)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
09-17 08:58:53.044: E/AndroidRuntime(10123): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.voxeet.toolkit.notification.CordovaFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.*.*-1/base.apk"],nativeLibraryDirectories=[/data/app/com.*.*-1/lib/arm64, /data/app/com.*.*-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-17 08:58:53.044: E/AndroidRuntime(10123): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3165)
09-17 08:58:53.044: E/An
droidRuntime(10123): 	... 8 more
09-17 08:58:53.043: I/Finsky(9149): [111] xue.a(109): Verifying installed packages
09-17 08:58:53.072: W/ActivityManager(1507):   Force finishing activity com.*.*/.MainActivity
09-17 08:58:53.080: I/Icing(8791): IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=SEARCH_CORPORA
09-17 08:58:53.089: I/Icing(8791): Removing corpus key com.google.android.music-top_tracks for package com.google.android.music
09-17 08:58:53.100: W/ActivityManager(1507):   Force finishing activity com.*.*/.MainActivity
09-17 08:58:53.100: W/ActivityManager(1507): Duplicate finish request for ActivityRecord{3fd8002 u0 com.*.*/.MainActivity t3 f}
09-17 08:58:53.178: I/Adreno(1507): QUALCOMM build                   : 7daed58, I7ece6fe30d
09-17 08:58:53.178: I/Adreno(1507): Build Date                       : 10/19/16
09-17 08:58:53.178: I/Adreno(1507): OpenGL ES Shader Compiler Version: XE031.09.00.03
09-17 08:58:53.178: I/Adreno(1507): Local Branch                     : missing_changes
09-17 08:58:53.178: I/Adreno(1507): Remote Branch                    : 
09-17 08:58:53.178: I/Adreno(1507): Remote Branch                    : 
09-17 08:58:53.178: I/Adreno(1507): Reconstruct Branch               : 
09-17 08:58:53.187: I/OpenGLRenderer(1507): Initialized EGL, version 1.4
09-17 08:58:53.187: D/OpenGLRenderer(1507): Swap behavior 1
09-17 08:58:53.219: W/atfg(8603): Empty context buffer. Thus might mean that the context is not synced down.
09-17 08:58:53.234: I/Finsky(9149): [174] com.google.android.finsky.sessionstats.SessionAndStorageStatsLoggerHygieneJob.a(42): Device Information privacy flag is unchecked
09-17 08:58:53.254: I/Finsky(9149): [174] sbv.a(28): jobFinished: 10-1. TimeElapsed: 881ms.
09-17 08:58:53.261: I/Finsky(9149): [1] sah.c(6): Job 10-1 finished. Not rescheduling.
09-17 08:58:53.266: I/Finsky(9149): [1] sah.a(22): Running job: 10-11
09-17 08:58:53.274: I/Finsky(9149): [1] sao.handleMessage(102): RunningQueue size: 4, PendingQueue size: 36
09-17 08:58:53.275: I/Finsky(9149): [1] sao.handleMessage(111): Running queue: 10-2 10-8 10-10 10-11 
09-17 08:58:53.299: I/Finsky(9149): [174] sbv.a(28): jobFinished: 10-10. TimeElapsed: 306ms.
09-17 08:58:53.302: I/Finsky(9149): [1] sah.c(6): Job 10-10 finished. Not rescheduling.
09-17 08:58:53.305: I/Finsky(9149): [1] sah.a(22): Running job: 10-12
09-17 08:58:53.307: I/Finsky(9149): [1] sao.handleMessage(102): RunningQueue size: 4, PendingQueue size: 35
09-17 08:58:53.308: I/Finsky(9149): [1] sao.handleMessage(111): Running queue: 10-2 10-8 10-11 10-12 
09-17 08:58:53.325: I/Finsky(9149): [174] com.google.android.finsky.splitinstallservice.SplitInstallCleanerHygieneJob.a(3): Running split install cleaner
```

**Comment by codlab** [comment]
Which version?

**Comment by youssmak** [comment]
Last version seems to fix things 👍
