### ISSUE TITLE
plugin installation issue

### ISSUE THREAD

**Issue by asadumair** [voxeet/voxeet-uxkit-cordova#73]
Hello i want to install plugin but these errors are there

Installing "cordova-plugin-voxeet" for ios
Installing Carthage dependencies... (this operation can take few minutes)
Error: Command failed: /Users/user/Desktop/Ionic Projects/Dolby/plugins/cordova-plugin-voxeet/carthage.sh update --platform ios --no-use-binaries --project-directory /Users/user/Desktop/Ionic Projects/Dolby/plugins/cordova-plugin-voxeet/src/ios
/bin/sh: /Users/user/Desktop/Ionic: No such file or directory

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '/Users/user/Desktop/Ionic Projects/Dolby/plugins/cordova-plugin-voxeet/carthage.sh update --platform ios --no-use-binaries --project-directory /Users/user/Desktop/Ionic Projects/Dolby/plugins/cordova-plugin-voxeet/src/ios'
}
/bin/sh: /Users/user/Desktop/Ionic: No such file or directory

Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-voxeet': CordovaError: Uh oh!
Cannot find framework "/Users/user/Desktop/Ionic Projects/Dolby/plugins/cordova-plugin-voxeet/src/ios/Carthage/Build/iOS/VoxeetUXKit.framework" for plugin cordova-plugin-voxeet in iOS platform
    at install (/Users/user/Desktop/Ionic Projects/Dolby/platforms/ios/cordova/lib/plugman/pluginHandlers.js:108:48)
    at ActionStack.process (/Users/user/Desktop/Ionic Projects/Dolby/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/user/Desktop/Ionic Projects/Dolby/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/Users/user/Desktop/Ionic Projects/Dolby/node_modules/cordova-common/src/PluginManager.js:142:21)
    at Api.addPlugin (/Users/user/Desktop/Ionic Projects/Dolby/platforms/ios/cordova/Api.js:254:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:561:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:344:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Uh oh!
Cannot find framework "/Users/user/Desktop/Ionic Projects/Dolby/plugins/cordova-plugin-voxeet/src/ios/Carthage/Build/iOS/VoxeetUXKit.framework" for plugin cordova-plugin-voxeet in iOS platform
[ERROR] An error occurred while running subprocess cordova.

i have cordova 11 and xcode 13.4

i already run this comand sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
but there is no success please help us.

**Comment by codlab** [comment]
Seems that it's because your path contains whitespace. Please check by renaming Ionic project to Ionic_project

**Comment by asadumair** [comment]
yes it works.
ThanYou
